CREATE TABLE import_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    file_name VARCHAR(255) NOT NULL,
    status VARCHAR(30) NOT NULL,

    total_records INTEGER NOT NULL DEFAULT 0,
    valid_records INTEGER NOT NULL DEFAULT 0,
    invalid_records INTEGER NOT NULL DEFAULT 0,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_import_batches_status
        CHECK (status IN ('PROCESSING', 'COMPLETED', 'FAILED')),

    CONSTRAINT chk_import_batches_counts
        CHECK (
            total_records >= 0
            AND valid_records >= 0
            AND invalid_records >= 0
        )
);