CREATE TABLE contribution_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    batch_id BIGINT NOT NULL,
    row_number INTEGER NOT NULL,

    employee_id VARCHAR(100) NOT NULL,
    contribution_month VARCHAR(7) NOT NULL,

    gross_salary NUMERIC(15, 2) NOT NULL,
    employee_contribution NUMERIC(15, 2) NOT NULL,
    employer_contribution NUMERIC(15, 2) NOT NULL,

    currency VARCHAR(3) NOT NULL,
    status VARCHAR(20) NOT NULL,

    CONSTRAINT fk_contribution_records_batch
        FOREIGN KEY (batch_id)
        REFERENCES import_batches(id)
        ON DELETE CASCADE,

    CONSTRAINT chk_contribution_records_row_number
        CHECK (row_number > 0),

    CONSTRAINT chk_contribution_records_status
        CHECK (status IN ('VALID', 'INVALID')),

    CONSTRAINT uq_contribution_records_batch_row
        UNIQUE (batch_id, row_number)
);

CREATE INDEX idx_contribution_records_batch_id
    ON contribution_records(batch_id);


CREATE TABLE validation_issues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    record_id BIGINT NOT NULL,
    code VARCHAR(100) NOT NULL,
    field_name VARCHAR(100),
    message VARCHAR(500) NOT NULL,

    CONSTRAINT fk_validation_issues_record
        FOREIGN KEY (record_id)
        REFERENCES contribution_records(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_validation_issues_record_id
    ON validation_issues(record_id);