spring.application.name=contribution-check-api

spring.datasource.url=jdbc:postgresql://localhost:5433/contribution_check
spring.datasource.username=contribution_user
spring.datasource.password=contribution_password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true

server.port=8080